name: attendance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI + Utilities
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  pie_chart: ^5.4.0
  shimmer: ^3.0.0

  # State management + Storage
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # API & Networking
  dio: ^5.9.0
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.5

  # Media
  image_picker: ^1.2.0

  # Nepali support
  nepali_utils: ^3.0.8
  nepali_date_picker: ^7.0.1

  # Loading + Overlay
  flutter_easyloading: ^3.0.5
  loader_overlay: ^5.0.0

  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true
  generate: true
  
  # Assets section should be here, inside the flutter section
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
